# Generated by Django 5.2 on 2025-05-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino")],
                db_column="Sexo",
                max_length=10,
                verbose_name="Sexo",
            ),
        ),
    ]
