# Generated by Django 5.2 on 2025-05-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoa", "0002_alter_funcionario_sexo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionario",
            name="id",
        ),
        migrations.AddField(
            model_name="funcionario",
            name="codigoFuncionario",
            field=models.SmallAutoField(
                db_column="CodigoFuncionario",
                primary_key=True,
                serialize=False,
                verbose_name="Código do Funcionário",
            ),
        ),
    ]
